In [1]:
A=[2,3,4]
a=[0,1,2]
A[0] -> 2
==0.0 float64 int8 0
B=[[1,2,3],[4,5,np.nan]]

C=[1,2,4]
  [4,5]

IndentationError: unexpected indent (1219251189.py, line 5)

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3]) #1-d
print(a)

[1 2 3]


In [6]:
#2-darray
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [10]:
a=np.array([1,2,3,4,5], dtype=complex)

In [11]:
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [15]:
#ndarray.shape
a=np.array([[1,2,3],[6,4,5]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [6 4 5]]


In [17]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[1 2]
 [3 6]
 [4 5]]
(3, 2)


In [20]:
#ndarry.ndim  #numpy.arange(start, stop, step, dtype)
a=np.arange(15)
print(a)
a=np.arange(15, dtype=float)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [25]:
b=np.arange(10,20,5)
print(b)

[10 15]


In [32]:
#numpy.linespace
x=np.linspace(10,20,5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [36]:
#numpy.itemsize
x=np.array([1,2,3,4,5], dtype=np.float64)
print(x.itemsize)

8


In [39]:
#Array creation
#np.empty(shape, dtype=float, order='C')
a=np.zeros(5, dtype=np.int)
print(a)

[0 0 0 0 0]


In [44]:
x=np.zeros((2,2), dtype=[('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [50]:
print(np.ones([5,5], dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [51]:
x=[1,2,3,4]
a=np.asarray(x, dtype=float)
print(a)

[1. 2. 3. 4.]


In [56]:
x=(1,2,3)
a=np.asarray(x)
print(a)
for i in x:
    print(i)

[1 2 3]
1
2
3


In [61]:
#Indexing & Slicing #start – stop – step 
a=np.arange(10)
print(a)
#slice
s=slice(2,7,2)
print(a[s])
print(a[5])
print(a[2:])
print(a[2:5]) #slic -> n-1

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
5
[2 3 4 5 6 7 8 9]
[2 3 4]


In [64]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print('\n')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[[3 4 5]
 [4 5 6]]


In [65]:
#arithmetic operation
a=np.array([1,2,3])
b=np.array([10,20,30])
c= a*b
print(c)


[10 40 90]


In [68]:
a=np.array([[0,0,0],[10,10,10],[20,20,20]])
b=np.array([1,2,3])
print(a)
print('\n')
print(b)
print(b+a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]]


[1 2 3]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [75]:
#iterating over array #Transpose
a=np.arange(0,60,5)
print(a)
print('\n')
a=a.reshape(3,4)
print(a)
print('\n')
print(a.T)
print('\n')
for x in np.nditer(a, order='C'):
    print(x)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


0
5
10
15
20
25
30
35
40
45
50
55


In [77]:
#array Manipulation
for x in np.nditer(a, order='C', op_flags=['readwrite']):
    x[...]=2*x

In [78]:
print(a)

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [81]:
#split
a=np.arange(9)
print(a)
b=np.split(a,3)
print(b)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [86]:
a=np.arange(16).reshape(4,4)
print(a)
print('n')
b=np.hsplit(a,2)
print(b)
print('n')
c=np.vsplit(a,2)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
n
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
n
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [89]:
#Append
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('\n')
print(np.append(a,[7,8,9]))
print('\n')
print(np.append(a,[[7,8,9]], axis=0))
print('\n')
print(np.append(a,[[7,8,9],[5,5,5]], axis=1))

[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3 7 8 9]
 [4 5 6 5 5 5]]


In [92]:
#insert
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(np.insert(a,3,[11,12]))

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 11 12  4  5  6]


In [95]:
#delete
a=np.arange(12).reshape(3,4)
print(a)
print('\n')
print(np.delete(a,5))
print('\n')
print(np.delete(a,1, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[ 0  1  2  3  4  6  7  8  9 10 11]


[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [97]:
#unique
a=np.array([5,2,3,2,4,4,5,8,9])
print(a)
u=np.unique(a)
print(u)

[5 2 3 2 4 4 5 8 9]
[2 3 4 5 8 9]


In [100]:
#numpy string function
print(np.char.add(['hello','hi'],[' world',' xyz']))

['hello world' 'hi xyz']


In [102]:
print(np.char.multiply(' hello',3))

 hello hello hello


In [103]:
print(np.char.title('hello world'))

Hello World


In [107]:
#sort
a=np.array([[3,7],[9,1]])
print(a)
print(np.sort(a, axis =0))

[[3 7]
 [9 1]]
[[3 1]
 [9 7]]
